resources:
- name: nimbus-cloud-bridge-instance
  type: compute.v1.instance
  properties:
    zone: us-west1-a
    machineType: zones/us-west1-a/machineTypes/n1-standard-1
    disks:
    - boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/debian-cloud/global/images/family/debian-9
    networkInterfaces:
    - network: global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
